# Security
security:
  basic:
    enabled: false

# Logging
logging:
  file: log.txt

#notifications
notifications:
  email:
    subject: Your training starts soon!
    textTemplate: Dear {0},<br/><br/>Your training starts at {1}. Don't forget about it!
    author:
      name: SwimHelper Notification System
      address: swimminghelper1@gmail.com
  scheduler:
    rate: 60000 #1 minute

#spring
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: swimminghelper1@gmail.com
    password: ${EMAIL_PASSWORD}
    protocol: smtp
    tls: true
    properties.mail.smtp:
          auth: true
          starttls.enable: true
          ssl.trust: smtp.gmail.com
  #Database
  h2:
    console:
      enabled: true
      path: /h2
  # Datasource
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
